### ISSUE TITLE
model not specified

### ISSUE THREAD

**Issue by cktsangal** [ppcool1163/question_answer_generator#1]
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-                                                                                                                                                               model-2017.09.15-charpad.tar.gz")
  File "/home/aim/ANDY-project/qa_gen-env/lib/python3.6/site-packages/allennlp/predictors/pred                                                                                                                                                               ictor.py", line 275, in from_path
    load_archive(archive_path, cuda_device=cuda_device),
  File "/home/aim/ANDY-project/qa_gen-env/lib/python3.6/site-packages/allennlp/models/archival                                                                                                                                                               .py", line 197, in load_archive
    opt_level=opt_level,
  File "/home/aim/ANDY-project/qa_gen-env/lib/python3.6/site-packages/allennlp/models/model.py                                                                                                                                                               ", line 391, in load
    model_class: Type[Model] = cls.by_name(model_type)  # type: ignore
  File "/home/aim/ANDY-project/qa_gen-env/lib/python3.6/site-packages/allennlp/common/registra                                                                                                                                                               ble.py", line 137, in by_name
    subclass, constructor = cls.resolve_class_name(name)
  File "/home/aim/ANDY-project/qa_gen-env/lib/python3.6/site-packages/allennlp/common/registra                                                                                                                                                               ble.py", line 185, in resolve_class_name
    f"{name} is not a registered name for {cls.__name__}. "
allennlp.common.checks.ConfigurationError: bidaf is not a registered name for Model. You proba                                                                                                                                                               bly need to use the --include-package flag to load your custom code. Alternatively, you can sp                                                                                                                                                               ecify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in                                                                                                                                                                which case they will be automatically imported correctly.

**Comment by ppcool1163** [comment]
Nice to hear from you Andy Tsang.
I have checked the model again on my system, I didn't receive any error. I will check this out again using another operating system. 
You can go to this link: https://colab.research.google.com/drive/1CgQ1_M55iuZ_Y9e4-yGw2RWe6AfXtgC6#scrollTo=_6dB5LmdPvPO  for the code I used for my reference.
OR
You can have a look at this youtube video: https://www.youtube.com/watch?v=5ZlAHHFeO4Y&t=159s
